# Generated by Django 5.2.4 on 2025-08-10 05:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_resource'),
        ('mining', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('passive_rate', models.DecimalField(decimal_places=8, default=Decimal('0.000001'), max_digits=20)),
                ('mine_duration', models.PositiveIntegerField(default=30)),
                ('yield_base', models.DecimalField(decimal_places=8, default=Decimal('0.001'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rigs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('yield_amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('coins_reward', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_jobs', to=settings.AUTH_USER_MODEL)),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='mining.ownedrig')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='MiningRig',
        ),
    ]
