# Generated by Django 5.2.4 on 2025-07-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_achievement_leaderboardentry_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics/'),
        ),
    ]
