# Generated by Django 5.2.4 on 2025-08-10 02:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_usd', models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=30)),
                ('volatility', models.FloatField(default=0.02)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=30)),
                ('remaining', models.DecimalField(decimal_places=8, max_digits=30)),
                ('status', models.CharField(choices=[('open', 'open'), ('filled', 'filled'), ('cancelled', 'cancelled')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_trades', to='market.order')),
                ('sell_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_trades', to='market.order')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('avg_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset_symbol')},
            },
        ),
    ]
