# Generated by Django 5.2.4 on 2025-08-10 05:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_value_usd', models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=20)),
            ],
        ),
    ]
