# Generated by Django 5.2.4 on 2025-08-10 05:26

import django.db.models.deletion
import users.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_resource'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_pic_path),
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=30)),
                ('crypto_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='market.cryptotoken')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shopitem')),
            ],
            options={
                'unique_together': {('user', 'shop_item')},
            },
        ),
    ]
